name: Test
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: mihaipe-sportsbet/actions-fundamendals-docker@v1
        with:
          who-to-greet: '@octocat'
